### ISSUE TITLE
Make our site searchable

### ISSUE THREAD

**Issue by galulex** [activebridge/old.activebridge.github.io#1]
[click](https://www.google.com.ua/search?q=Active+Brdige&oq=Active+Brdige&aqs=chrome..69i57j0l3j69i60.6193j0j1&client=ubuntu-browser&sourceid=chrome&ie=UTF-8#q=Active+Bridge&spell=1)

**Comment by Alexey-Lukin** [comment]
https://github.com/activebridge/activebridge.github.io/commit/90840b64b0e1035b6fcbe8293dfafe195c2f7b20
https://github.com/activebridge/activebridge.github.io/commit/4216ba66e0834c97b0f7dc9c92f7140aec5345ba
